name: task on github
on: [push]
jobs:  
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: task for deploying
        uses: kartikgaurkg/Github-actiobs@master
        env:
          HOST: "3.19.120.1"
          USERNAME: "ec2-3-19-120-1.us-east-2.compute.amazonaws.com"
          PORT: 22 80 443
          KEY: ${{ secretsKEY }}
        with:
          source: "kartikgaurkg/Github-actiobs/first"
          target: "/var/www/html"
         
